// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Avatar: typeof import('./components/Avatar/Avatar.vue')['default']
    Button: typeof import('./components/Button/Button.vue')['default']
    CheckboxButton: typeof import('./components/Checkbox/CheckboxButton.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Input: typeof import('./components/Input/Input.vue')['default']
    ListItem: typeof import('./components/List/ListItem.vue')['default']
    PlanBubble: typeof import('./components/Organism/PlanBubble.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
